<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\GammeController::add' => function () {
    return ($this->privates['.service_locator.GaSCbpf'] ?? $this->load('get_ServiceLocator_GaSCbpfService.php'));
}, 'App\\Controller\\NoteController::addNote' => function () {
    return ($this->privates['.service_locator.1kziBYP'] ?? $this->load('get_ServiceLocator_1kziBYPService.php'));
}, 'App\\Controller\\NoteController::index' => function () {
    return ($this->privates['.service_locator.1kziBYP'] ?? $this->load('get_ServiceLocator_1kziBYPService.php'));
}, 'App\\Controller\\SecurityController::registration' => function () {
    return ($this->privates['.service_locator.t7BdSgs'] ?? $this->load('get_ServiceLocator_T7BdSgsService.php'));
}, 'App\\Controller\\GammeController:add' => function () {
    return ($this->privates['.service_locator.GaSCbpf'] ?? $this->load('get_ServiceLocator_GaSCbpfService.php'));
}, 'App\\Controller\\NoteController:addNote' => function () {
    return ($this->privates['.service_locator.1kziBYP'] ?? $this->load('get_ServiceLocator_1kziBYPService.php'));
}, 'App\\Controller\\NoteController:index' => function () {
    return ($this->privates['.service_locator.1kziBYP'] ?? $this->load('get_ServiceLocator_1kziBYPService.php'));
}, 'App\\Controller\\SecurityController:registration' => function () {
    return ($this->privates['.service_locator.t7BdSgs'] ?? $this->load('get_ServiceLocator_T7BdSgsService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
