<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.PluLMwD.App\Entity\Note' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.PluLMwD": it references class "App\\Entity\\Note" but no such service exists.');
