<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKrCXvTY\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKrCXvTY/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKrCXvTY.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKrCXvTY\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKrCXvTY\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KrCXvTY',
    'container.build_id' => 'a381f297',
    'container.build_time' => 1541551833,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKrCXvTY');
