<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKjlRfVo\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKjlRfVo/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKjlRfVo.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKjlRfVo\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKjlRfVo\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KjlRfVo',
    'container.build_id' => 'eda2dd86',
    'container.build_time' => 1540213089,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKjlRfVo');
