<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRG6ffi7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRG6ffi7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRG6ffi7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRG6ffi7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerRG6ffi7\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'RG6ffi7',
    'container.build_id' => '649ad2cb',
    'container.build_time' => 1540259928,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRG6ffi7');
